@startuml
#SkyBlue:Отправляет закладку;
note right
Действия пользователя
end note
:Определяем тип закладки;
note left
Действия приложения
end note
If (У сообщения есть тэги?) then (Да)
:Сохраняем тэги;
endif;
If (Сообщение - ссылка?) then (Да)
:Добавляем источник в тэги;
endif;
:Находим все категории;
:Отрисовываем сообщение и кнопки категорий;
:Отправляем пользователю;
If (В списке есть подходящая категория?) then (Да)
#SkyBlue::Нажимает на кнопку категории;
else (Нет)
#SkyBlue:Нажимает на кнопку "Новая категория";
#SkyBlue:Вводит название категории;
#SkyBlue:Нажимает отправить;
endif;
:Закладка сохранена;
note left
Отображаем закладку
со всеми атрибутами,
под закладкой отображаем
кнопку для удаления
end note
@enduml