@startuml
#SkyBlue:Открываем\nприложение;
note right
Действия пользователя
end note
#SkyBlue:Нажимаем "Поиск";
#SkyBlue:Выбираем тип поиска:\n- по типам закладок\n- по категориям\n- по тэгам\n- по ключевым словам;
split
    :**По типам закладок**;
    :Приложение отображает\nдоступные типы;
    note left
    Действия приложения
    end note
    #SkyBlue:Выбираем нужный тип;
split again
    :**По категориям закладок**;
    :Приложение отображает\nдоступные категориям;
    #SkyBlue:Выбираем нужную категорию;
split again
    :**По тэгам**;
    :Приложение отображает\nдоступные тэги;
    #SkyBlue:Выбираем нужный тэг;
split again
    :**По ключевым словам**;
    :Приложение предлагает\nввести ключевые слова;

    #SkyBlue:Вводим ключевые слова;
end split
#SkyBlue:Нажимаем "Найти";
if (Закладки нашлись?) then (Да)
:Отображаем найденные закладки;
note
Отображаем по 10 закладок на странице
и кнопки навигации под сообщением;
end note
#SkyBlue:Нажимает на нужную закладку;
:Отображаем выбранную закладку;
stop
else (Нет)
#pink:Отображаем "Заметки не найдены!";
stop
@enduml